### ISSUE TITLE
[Bug][AVS] Incomplete score array from backend

### ISSUE THREAD

**Issue by mpas97** [lucaro/DRES#100]
The scores in graphs are wrong. Not the same points, not the right user.

* The `vitrivr & SOM I` user made some points here but as we can see the only user in the left graph is `vitrivr I` who got all points.
* Second, the right graph only has one big bar over all users that seems wrong too.
* Third, shouldn't we see 75 AVS task points there (instead of 100) as it has been the first AVS task?

<img width="1471" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84158392-1c86af00-aa6c-11ea-9394-ccf740796879.png">

**Comment by lucaro** [comment]
Which version are you using? The issues with bullets 1 and 2 should have been fixed a while ago, so I would be rather surprised if they were present in the current version. If you are using the most recent version, we would need to investigate this. As for bullet 3, this is correct behavior as scores are normalized to 100 points within task groups. The highest scoring user per task group will hence be awarded 100 points and since in your example, only one user scored any points, they get the maximum score by default.

**Comment by silvanheller** [comment]
67f66c722295b98e4ad231fe9f5f6ad7e7f9287b, so the only commit since then has been 16309633d40c5f27ecc0a6b54955e7888431e289

**Comment by lucaro** [comment]
Interesting, we'll see if we can reproduce this...

**Comment by sauterl** [comment]
I just updated the title of this issue. For KIS tasks, the scores work as intended.
However, the backend returns incomplete score arrays for AVS tasks, as can be seen in the following response:

```
[
  {
    "name": "TKIS",
    "taskGroup": "TKIS",
    "scores": [
      {
        "teamId": 0,
        "score": 100
      },
      {
        "teamId": 1,
        "score": 0
      }
    ]
  },
  {
    "name": "VKIS",
    "taskGroup": "VKIS",
    "scores": [
      {
        "teamId": 0,
        "score": 100
      },
      {
        "teamId": 1,
        "score": 0
      }
    ]
  },
  {
    "name": "AVS",
    "taskGroup": "AVS",
    "scores": [
      {
        "teamId": 0,
        "score": 100
      }
    ]
  },
  {
    "name": "average",
    "taskGroup": null,
    "scores": [
      {
        "teamId": 0,
        "score": 100
      },
      {
        "teamId": 1,
        "score": 0
      }
    ]
  }
]
```

**Comment by sauterl** [comment]
97b3feb0dc4488140680a2d303c53e925e35f70b fixes the issue from bullet two.

@mpas97 your first bullet / issue is not reproducible anymore, it might got fixed.
However, if you can reproduce it I would like you to file another issue with instructions on how to reproduce it.
