### ISSUE TITLE
is judgment open value correct?

### ISSUE THREAD

**Issue by mpas97** [lucaro/DRES#105]
Should the open field not be the amout of accualy being judged items? Here 1 (the one currently open, single judge)? For me pending is "how many are in the queue" and open "how many of them are currently displayed to a judge". Because 30 is 31-1 it would mean: open = total queue minus the open ones.
<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84251058-1d235200-ab0d-11ea-95ca-dcd27599bdbb.png">

**Comment by sauterl** [comment]
Open is the amount of submissions still to `judge` (i.e. no judge has seen yet), `pending` is the amount submissions a verdict is awaited.
I'll add more detailed information soon.
