### ISSUE TITLE
[Bug] finished task produces some null values

### ISSUE THREAD

**Issue by mpas97** [lucaro/DRES#106]
When I open the page, when the task was already done.
<img width="1674" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84252642-244b5f80-ab0f-11ea-9b1a-9db522547053.png">

Sometimes the error also looks like this, not sure when this happens exaclty. 
<img width="1674" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84250673-9ec6b000-ab0c-11ea-84f9-06f3a66b38c1.png">

**Comment by sauterl** [comment]
I can confirm this behaviour. More than this, generally the viewer throws these errors when no task-preview-video is playing.
