### ISSUE TITLE
Error in promise

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#111]
As a follow-up of #106 _sometimes_ the viewer throws `Error in promise` for the video when the task is over and no video should be played

**Comment by lucaro** [comment]
I'm certain to have observed this in AVS tasks. It is however apparently not consistent behavior.

**Comment by ppanopticon** [comment]
Do we know for a fact that the video player is causing this issue? Or what makes your think that this could be the case?

**Comment by sauterl** [comment]
@ppanopticon no, it's not a known fact that the video player causes this issue. However, as described above, it occurs when there is no video to play (semantically, e.g. the task is over, there is no video to play (AVS))

**Comment by ppanopticon** [comment]
Okay since I have no idea what else might be causing the issue, I have wrapped all the audio effect playback into a dedicated utility class that handles playback errors.

If this error does not occur anymore, then this might have been the cause. So we should try to keep an eye out for this issue.

**Comment by ppanopticon** [comment]
Seems to be fixed!
