### ISSUE TITLE
Housekeeping Task Viewer

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#112]
Various housekeeping things in the frontend:

- [x]  Horizontal scrollbar for team-score view is always present
- [x] Debounce task state queries (this is an issue, if many submissions are made in batch style)
- [x] Previews: Have a placeholder (instead of the missing)
- [x] Previews: Regularly update (in case the backend has produced them)

- [x] Add visual highlight to new submission/submitting team
- [x] Sort bar charts by score

**Comment by lucaro** [comment]
I added two more items to the list, based on experiences of the last evaluation.

**Comment by ppanopticon** [comment]
Ad number two (Debounce task state queries..."): Am I assuming correctly, that you mean **RunState** instead of task state?

**Comment by sauterl** [comment]
> Ad number two (Debounce task state queries..."): Am I assuming correctly, that you mean **RunState** instead of task state?

I think you are right, proper wording would have been "Debounce task viewer's run state queries"

**Comment by lucaro** [comment]
I'd suggest to move 'Add option to force-scale team information to fit on screen' to a new issue, together with centring of the team boxes in case there are fewer than the width and the polishing of the score display.

**Comment by sauterl** [comment]
Moved 'Add option to force-scale team information to fit on screen' to #142
