### ISSUE TITLE
White on white graph coloring

### ISSUE THREAD

**Issue by mpas97** [lucaro/DRES#114]
<img width="1593" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84405354-4c6ab980-ac08-11ea-8158-c53dfb968eef.png">

**Comment by mpas97** [comment]
For the vitrivr1 user on the right, we have a white score on a white background.

**Comment by sauterl** [comment]
Works as intendet. Dark theme results in a high-contrast font-color, specifically white.
Thus, this is unfortunate, but an issue that only the admin can fix by using a different color.

**Comment by mpas97** [comment]
Okay, then I was wrong. I assumed that as on the left, all bars should get the same color.
