### ISSUE TITLE
Implement More Audio Indication

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#120]
Implement the sounds added in #119 

 - [x] TKIS Description Change
 - [ ] Task: Time over soon (e.g. last 30 seconds)

**Comment by ppanopticon** [comment]
Regarding the second part of the requirement:

1. Should this be an audio clip that keeps on playing until the task is complete (e.g. a piece of dramatic music) OR a one-time cue?
2. In case of a one-time cue; when exactly? Only once? Or maybe once at 1 minute and once at 30 seconds?

**Comment by lucaro** [comment]
I rather thought of it being a cue, to draw attention to the dwindling time. If only one sound is to be played, maybe play it once at T-1min and twice at T-30sec? Having more than one sound would also be an option.

**Comment by ppanopticon** [comment]
Done!
