### ISSUE TITLE
[Judgement View] User Interaction / Keep Alive Trigger

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#121]
In order to play the videos in the Judgement View, the user has had to interact with the browser before (security feature of modern browsers). To enforce user interaction, a dialog could be added to the judgement view with a small exercise to get the user's attention (and have the required user interaction).

Additionally, to only send judgement requests to _active_ judges, a keep alive mechanism will be implemented:
Each judgement verdict is a user interaction that resets a timer, if the timer runs out, this judge will not receive new judgement requests.

 - [ ] **View** Add Welcome Exercise
 - [ ] **View** Add timer and timeout

**Comment by lucaro** [comment]
The judgement views polls submissions to be judged. I don't see the need for any backend change in this case, since it does never push anything.

**Comment by sauterl** [comment]
Yes, the backend does not need any changes.
Initially, I thought this would be a good time to prepare #83 however, we should not mix issues here.
I adjusted the issue description and project assignment, thanks for the comment!
