### ISSUE TITLE
[Architectural Change] Multi-modal, multimedia task description

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#122]
**Main Change for Milestone `0.3-alpha`**

Currently, _visual_ and _textual_ KIS tasks have a visual and textual task description, respectively.
In order to be more flexible, a multi-modal, multimedia task description is required:

A task has description _slots_:
- textual
- visual (i.e. video and / or image)
- audio

Each slot can have a sequence of different items, each specified by a temporal offset from the task start time. The combination of task description slots is based on the task group.

Results in changes in the frontend and backend:

 - [x] **View** Adjust Create Task View
 - [x] **View** Adjust Task Viewer
 - [x] **Backend** Rework task description model

**Comment by lucaro** [comment]
See https://github.com/lucaro/DRES/tree/feature/task-presentation-redesign
