### ISSUE TITLE
Redesign handling/management of interaction and result logs

### ISSUE THREAD

**Issue by lucaro** [lucaro/DRES#133]
Currently, all the log data is stored in the task run data, which is kept in memory during the entire run. This leads to a unreasonably large memory requirement without any benefit. I would therefore suggest to handle the logs in a streaming manner, performing analysis (if any) without keeping the messages in memory for extended periods of time and then flush everything to disk as soon as possible. The question would then just be if this processing should happen in 'the loop' or in a dedicated mechanism. Opinions?

Subtasks originally posted in #143 but relevant for this one:

 - [x] Better de-/ serialization error message propagation. Ideally directly to the caller
 - [x] Encapuslate these logs and enhance with `runId`, `IP`, `sessionID` and `timestamp` (server) and store that as JSON to disk (notably not in the db)
 - [x] dedicated stream processing engine for log endpoint handling
 - [ ] Provide better validation (might be better a dedicated issue)
 - [ ] Potentially offer log validation service in ui (might be better a dedicated issue)

**Comment by sauterl** [comment]
Based on our discussions and as described in #143 the dedicated mechanism is set.
