### ISSUE TITLE
Sound debouncing: Correct submission is more important

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#137]
Currently, the debounce of sound effectcs does not consider a hierarchy or "importance".
Ideally, there are more important sounds than others, e.g. in doubt, play the correct submission sound instead of the incorrect one, as this might confuse participants

**Comment by ppanopticon** [comment]
Currently I'm debouncing two subsequent calls to the submission endpoint with an offset of 100ms (previously 500ms). If within such a call, a correct submission occurs, that submission was and still is prioritised for audio playback. 

That's imho all I can do. I cannot debounce the calls to the API based on what the APIs would return.
