### ISSUE TITLE
Soft redesign: Viewer and Participants roles

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#138]
Competition Run based config whether `participant`s are able to see the run viewer or not, while users with the role `viewer`, certainly are allowed to see the run viewer.

 - [x] Data model change: Flag on competition run
 - [ ] Adjust UI -- Competition Run
 - [ ] Adjust UI & Respect flag in UI: Task Viewer / Prevent task viewer showing

**Comment by lucaro** [comment]
Ideally, the video would also go into fullscreen for the first loop. There is a way to request this from the browser, see https://www.w3schools.com/howto/howto_js_fullscreen.asp for reference.
