### ISSUE TITLE
Configurable auto mute after n loops

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#141]
As the latest evaluation using DRES has shown, playing the same 20 seconds video clip with the same audio in loop is pretty annoying. Frontend-configurable (potentially per-user) or auto-mute after _n_ loops would be appreciated

**Comment by lucaro** [comment]
Ideally, the video would also be shown in fullscreen for the first loop. This can not be forced but only requested, see https://www.w3schools.com/howto/howto_js_fullscreen.asp for reference.

**Comment by ppanopticon** [comment]
Mute functionality added. The question remains, where exactly we would like to configure this: Is this a fronted setting or specific to the task or even the user?

**Comment by lucaro** [comment]
Too bad about the fullscreen. As for the mute, I think it can be hardcoded for now and then we can see if there is a need to make this user configurable.

**Comment by ppanopticon** [comment]
So then this issue is closed!
