### ISSUE TITLE
[Architectural Change] Interaction and Result Log management

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#143]
We have experienced in the latest evaluation, that interaction & result logs (the `/logs` endpoint) shall handle those logs differently than currently implemented. These are some of the envisioned changes:

 - [ ] Better de-/ serialization error message propagation. Ideally directly to the caller
 - [ ] Encapuslate these logs and enhance with `runId`, `IP`, `sessionID` and `timestamp` (server) and store that as JSON to disk (notably not in the db)
 - [ ] dedicated stream processing engine for log endpoint handling
 - [ ] Provide better validation
 - [ ] Potentially offer log validation service in ui

**Comment by lucaro** [comment]
What's the difference between this and #133 ?

**Comment by sauterl** [comment]
I personally felt like #133 was the place for a discussion and this one would have been for tracking the progress. Nevertheless, let's close this one and keep further discussions (if they arise) and progress tracking on #133 .
