### ISSUE TITLE
[Task Create] Bugfixes and QoL Improvements

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#144]
**Depends on: #122**

Re-add video player and fix below mentioned bugs / feature requests

Further improvement for task creation UI:

 - [x] ~~**Bug** Timestamps cannot be used as the input is numeric~~ _(We removed the timestamp unit)_
 - [x] **Bug** Always allow randomized media item selection
 - [ ] **Bug** Cancel old media item autocomplete requests upon new ones
 - [ ] **Bug** Reload video player setup upon changes
 - [ ] Video player: Button for current video position as start
 - [ ] Video player: Button for current video position as end
 - [ ] Video player: Button for toggling looping

**Comment by lucaro** [comment]
Also, an option to set the player to loop the selected time interval would be useful.
