### ISSUE TITLE
[Task Description Rework] Task Creation UI

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#145]
Tracking progress of the create-UI part of #122 

- [x] Task Type
- [x] Task Group
- [x] Task

  * [x] Component Type: Text
  * [x] Component Type: Image (Media Item)
  * [x] Component Type: Video (Media Item)
  * [x] Component Type: Image (External)
  * [x] Component Type: Video (External)
  * [x] Target Type: Single Media Item (whole)
  * [x] Target Type: Single Media Segment (with Range)
  * [x] Target Type: Multiple Media Items
  * [x] Target Type: Judgment

**Comment by lucaro** [comment]
Target Type Single Media Item can currently be created but causes errors when the competition is to be saved.

**Comment by ppanopticon** [comment]
> Target Type Single Media Item can currently be created but causes errors when the competition is to be saved.

I cannot confirm this behaviour. Is this still an issue?

**Comment by lucaro** [comment]
no, this should be fixed.

**Comment by ppanopticon** [comment]
Then we can close #145
