### ISSUE TITLE
Consistency in API operation naming

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#148]
Currently, there are various naming schemes for API operations:

 * `GET /api/competition` actually _lists_ all competition**s**
 * `GET /api/competition/{competitionId}/team` actually _lists_ the team**s** of a competition
 * `GET /api/competition/{competitionId}` returns the competition specified
 * `GET /api/user/list` actually _lists_ all user**s**
 * `GET /api/user/{id}` returns the user specified
 * `GET /api/collection/list` actually _lists_ all collection**s**
 * `GET /api/run/admin/{runId}/viewers` actually _lists_ all the viewer**s** (note the plural)

I'd like to enforce consistency following this simple logic:

 * `GET  */<entity>/{<entityId>}` with entity being an entity of the system in singular, i.e. like currently `/api/competition/{competitionId}`, returning the entity specified. **Note the _id_ is prefixed with the entity name**
 * `GET */<entity>/list`  with entity being an entity of the system in singular, returning a list of all of these entities
 * Above naming scheme applies also for nested / context sensitive entities (e.g. the viewers in the above example)
 * REST conventions for `POST`, `PATCH` and `DELETE` methods apply

I personally like the above scheme, because collections are obvious with the `/list` suffix, while a plural **s** could get missed

Opinions?

**Comment by lucaro** [comment]
Sounds reasonable
