### ISSUE TITLE
Serious Bug in Starting a new Run for a Competition

### ISSUE THREAD

**Issue by klschoef** [lucaro/DRES#174]
When starting a new run for a competition (e.g., "LSC2020 Test" as name" and "SYNCHRONOUS" as type) the server responds with a toast message "Error: Index 7367 out of bounds for length 2"

**Comment by lucaro** [comment]
Could you please provide additional detail, such as backend logs and the database contents, in order to allow for reproduction of the issue?

**Comment by ppanopticon** [comment]
The bug seems to be related to a corrupted _runs.db_ file. Removing runs.db should fix the problem.

As to what caused the corruption; we're not quite sure (yet). However, we added a rollback() mechanism to the DAOs involved in case something goes wrong during serialisation.

**Comment by lucaro** [comment]
Since we could not reproduce this and hence stabilized the database logic, I'll close this for now.
