### ISSUE TITLE
Beautification

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#18]
- [x]  Visual KIS Task: Adjust Ration / screen estate to actual video player
-  ~~Adjust / Re-think used icons~~ See #33 
- [x] Textual KIS Task: Line-spacing
- [x] Responsive tables
- [ ] ...

(This issue might be expanded with other beautification tasks)

**Comment by ppanopticon** [comment]
Fixed display glitches with video player & text view.

**Comment by ppanopticon** [comment]
Regarding icons: I'd suggest we go through the icons and discuss this in a Skype session

Unfortunately, I can't recall what is meant by "responsive tables".

**Comment by sauterl** [comment]
Iirc, the 'responsive tables' were specifically referring to the competition builder view, which I guess was more or less fixed in the meantime by you...

**Comment by ppanopticon** [comment]
Done!
