### ISSUE TITLE
Internal information representation

### ISSUE THREAD

**Issue by ppanopticon** [lucaro/DRES#29]
Sometimes I stumble over indirections regarding how we represent and use information internally. For example, a _collection_ can be identified by both its name or its internal ID and we use either one or the other, depending on the API implementation. 

Or time in a video can be expressed in milliseconds or as time code (and many more variants). And again, we allow for or expect a certain representation in certain areas of the stack.

I think we should identify the relevant entities, agree upon an internal representation and then make sure, that we stick to this representation. For example, I'd suggest to use milliseconds to address time in a video and with the exception of specific APIs that explicitly allow for other representations (e.g. submission), that's the representation that we use and expose.

Same goes for collection (name vs. ID), media item (name vs. id), tasks etc. I guess at first we should collect all the relevant entities in this issue and then in a second step make sure, that all the APIs use the representation we agreed upon.

**Comment by sauterl** [comment]
This issue was addressed in #146
