### ISSUE TITLE
[Bug] Task Edit: (TKIS) default delay not shown in ui

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#34]

**Comment by ppanopticon** [comment]
Should this default delay be hard-coded? I don't see a default delay in our data model.

**Comment by lucaro** [comment]
`KisTextualTaskDescription` does have a delay parameter, which by default is set to 30, see https://github.com/lucaro/DRES/blob/master/backend/src/main/kotlin/dres/data/model/competition/TaskDescription.kt#L52

**Comment by ppanopticon** [comment]
Yea I saw that. Maybe my question was ill-posed: This value is hard-coded in the back-end, hence I'll need to hard-code it in the front-end as well. Question was more in the direction of whether there should be an explicit setting somewhere in the data model.

But I'll use that value for now then.

**Comment by ppanopticon** [comment]
Fixed!
