### ISSUE TITLE
[Bug] Running Task View minor issues

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#38]
This is a collection of minor issues in the task view of a running task:

 - [x] Weird `?` instead of submission in submission box
 - [x] Frames not properly shown (i.e. the previews are not shown)
 - [ ] Video of previous task was shown (potentially related to #37 )

**Comment by ppanopticon** [comment]
What exactly was the issue with the second bullet? I can't remember that there was an issue with the frames not being shown properly.

**Comment by sauterl** [comment]
iirc the second bullet referred to textual kis tasks, as the frames were not shown once the task was completed. If it works now, don't bother...

**Comment by ppanopticon** [comment]
Mhm okay this seems to be working now.

**Comment by sauterl** [comment]
Nice, this closes #25 then 👍

**Comment by ppanopticon** [comment]
Indeed!
