### ISSUE TITLE
[Bug] Task Scoreboard shows current score

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#39]
Currently, the 'Task Scoreboard' shows the score of the current task as a bar chart -- this is useless as the score is also shown per team in the submission box below.

Make this scoreboard show the scores _of the current task category_

Requires some modification of the endpoint

**Comment by lucaro** [comment]
Score endpoint was extended in https://github.com/lucaro/DRES/commit/7b608f78ded0210bba55b3423860ac23457454aa
