### ISSUE TITLE
[Bug] Task Viewer: Video Autoplay Issues

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#44]
The autoplay of visual KIS tasks is instable: sometimes it works, sometimes not.
There seems to be a security issue, at least partially.

This [source](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) could help here

**Comment by ppanopticon** [comment]
As I'm gathering from the aforementioned documentation, there is no perfect solution here. The autoplay blocking is pretty strict and affects both <audio> and <video> with an audible audio track.

- Muting is our best shot and the simplest option available, which we can implement.
- Overriding the browser security settings or whitelisting a domain are a bit more difficult to enforce.
