### ISSUE TITLE
Textual KIS -- Play correct segment upon completion

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#56]
The title

**Comment by ppanopticon** [comment]
This is currently blocked by how **GetMediaHandler** is implemented! It expects the name of the collection but I only have the collection's ID in the MediaItem.

This is related to #29.

**Comment by lucaro** [comment]
I see three options to address this, which one would you prefer?

1. Change the SubmissionInfo object to contain the collection information directly (and probably also not return MediaItem instances but rather a proxy thereof)
2. Add metadata endpoints which return information about collections (and media items) by Id
3. Add an endpoint which returns the pre-rendered video (which we already have anyway) for the task specifically

**Comment by ppanopticon** [comment]
I'd argue that 1) would be desirable irrespective of this concrete issue.

Simplest solution for me would be 3). It would mean that I can use the already existing endpoint. Only thing we need to do in this case is pre-generate these previews for KIS Textual tasks as well.
