### ISSUE TITLE
Deletable Runs

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#59]
Make runs

- [x] Deletable (even before they are started)
- [x] Cancelable

**Comment by ppanopticon** [comment]
Frankly, I'm not exactly sure what is meant by "deletable" and "cancelable". Do you mean the ability to terminate a run? And if yes, where's the difference between "deletable" and "cancelable"?

**Comment by lucaro** [comment]
I don't see the difference here either. There is already the possibility to end a run, so having the possibility to subsequently also delete it should be sufficient, right?

**Comment by sauterl** [comment]
I agree with you. I guess the two bullets are an artefact of our discussions.
The system would benefit from **deletable** runs, which, however, are always deletable. Hence, non-started runs would be __cancelable_ 😉

**Comment by ppanopticon** [comment]
With the changes in #62 it should now be possible to terminate a run in ever state (unless a task is being executed). Furthermore, there is now a CLI command to delete runs.
