### ISSUE TITLE
Competition viewer: Finalize team overview component

### ISSUE THREAD

**Issue by ppanopticon** [lucaro/DRES#6]
- [x] Display current score summary per team
- [x] Proper layout & styling
- [x] Display a summary of the per-team submissions + information which tool submitted

**Comment by lucaro** [comment]
I think it would also be interesting to visualize the tool-id somehow, to make it visible which of the multiple instances of a tool was responsible for a submission.

**Comment by ppanopticon** [comment]
Agree! I just updated the issue accordingly.

**Comment by ppanopticon** [comment]
Done!
