### ISSUE TITLE
[Bug] Task Change: Scores and Submissions remain in UI

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#60]
The team section of the task viewer does not update (i.e. reset) the submission display

**Comment by ppanopticon** [comment]
This is currently solved as follows: The UI track which task has ended last and displays the elements only if that task is currently the 'active' task. This solution comes with the downside, that it only works for UI instances that actually lived through the event of a task ending (i.e. that information is lost after a reload).

Frankly, I'm not convinced that this is the right solution. It's probably something that the backend should make sure of by checking if the currently active task and the last task run are the same and returning submissions + scores accordingly.

Any thoughts on this?

**Comment by lucaro** [comment]
I'd argue that the UI should be as stateless as possible and receive all relevant information from the backend without having to track anything itself (except maybe in order to react to real-time events which would be lost with a reload anyway). What API changes would we need in order for the UI to get the relevant state changes from the backend?

**Comment by ppanopticon** [comment]
I guess it's less about changing the API structurally but about changing its semantic. Basically it boils down to only returning information if either a task is running OR the current task (navigation) is equal to the task of the current task run.

For example, for the **SubmissionInfoHandler**:

```kotlin
return if(run.status == RunManagerStatus.RUNNING_TASK) {
   if(run.currentTask is HiddenResultsTaskDescription) {
     submissions.map { SubmissionInfo.blind(it) }
   } else if (run.currentTask == run.currentTaskRun.task) {
     submissions.map { SubmissionInfo(it) }
   } else {
     SubmissionInfo()
   }
```
But it would also affect the **CurrentTaskScoreHandler* and potentially others.

On a higher level it's about having a well defined interplay between the "navigational" part of the RunManager (e.g. which task is currently highlighted) and the task runs themselves.

**Comment by lucaro** [comment]
There are currently some inconsistencies in the behavior of the API in that respect. I would suggest that for a v0.2 milestone, we should re-examine the entire state space with its relevant transitions and make sure that all affected API calls behave reasonably and consistently depending on the state a run is in.

**Comment by ppanopticon** [comment]
Solved for now. See #67 for follow-up discussions.
