### ISSUE TITLE
Revisit dynamics between navigational state of RunManager and state of individual task runs in terms of API responses

### ISSUE THREAD

**Issue by ppanopticon** [lucaro/DRES#67]
This is a follow-up of #60 

We should revisit how certain API endpoints such as **SubmissionInfoHandler** or **CurrentTaskScoreHandler** interact with the navigational state of the RunManager. 

For example, once a task run has completed, what are the conditions that should be met for those API endpoints to still return _submissions_ and _scores_ for the completed run.

One idea would be, that these (and similar endpoints) only return the scores of a completed run if the task in the navigational state is equal to the task in the completed run. Advantage of this approach is that is can be realised without changing the inner workings of the RunManager. However, other solutions may be possible as well.

Goal of this enhancement is to minimize the statefulness of the UI because currently, the UI must decide itself whether to, e.g., display the scores for a completed run based on the history of events. Even though this somehow works, it is not desired to be that way. See #60 for more information.

**Comment by ppanopticon** [comment]
Looking at this issue, I think we have solved some of the mentioned challenges by introducing an additional state for when a task has just ended. 

Is it safe to say, that **SubmissionInfoHandler** and **CurrentTaskScoreHandler** should only return submissions and scores of the current TaskRun in the phases _TASK_PREPARE,_ _TASK_RUNNING_ and _TASK_ENDED_? In all the other cases, they'll return empty lists or zero.

**Comment by ppanopticon** [comment]
Maybe a word as to how I would implement this: It probably makes sense that navigation away from a task in the state TASK_ENDED should null the CompetitionRun.currentTask. 

Hence instead of assuming that the current _TaskRun_ is just the last element in the list of TaskRuns, it should be an explicit pointer to a TaskRun instance that is set when the task starts (TASK_PREPARE) and remains valid until the task has ended (TASK_ENDED) and someone decides to navigate to the next task.

**Comment by lucaro** [comment]
That sounds reasonable, it might however break some other handlers which use the currentTask as a lastActiveTask. I'd argue to just let them break and then figure out solutions for all affected cases, but doing that for the 0.2 milestone might not be such a good idea...

**Comment by ppanopticon** [comment]
Agree! Maybe we should move this issue to 0.3-alpha. Especially, since there are some other architectural questions that I have spotted while working on this. For example:

SynchronousRunManager.taskRunData probably won't behave as expected since addressing a TaskRun by TaskId is futile. There might (in theory) be multiple TaskRuns for a given TaskId, e.g., in case of a repetition.

**Comment by lucaro** [comment]
Yes, this would probably also be a good opportunity to address the internal vs external id strategy. I already introduced UIDs for several data structures a while back which are intended to be used for external references, but this process is not complete yet.

**Comment by ppanopticon** [comment]
ToDo's:
[x] Make API calls aware of the navigational and executional state.
[ ] Expose external UIDs

**Comment by sauterl** [comment]
Addressed in #146
