### ISSUE TITLE
[Judgement View] Make preview longer

### ISSUE THREAD

**Issue by ppanopticon** [lucaro/DRES#75]
Preview videos (of presumably individual or a range of frames that have been submitted) tend to be very short. I think it would make sense to give a preview of at least 2s around the submitted frame so as to prevent rounding errors etc. to hinder the judge in reaching a clear verdict.

**Comment by sauterl** [comment]
Play at least a few seconds of every submission, if necessary add padding

**Comment by sauterl** [comment]
Implemented in 9b5195d52677feccc427492db9185da54dc6d997
