### ISSUE TITLE
[Run Admin View] Create dedicated admin view for runs

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#77]
Bugs of the current run admin view to address in this rework:

 - [x] All rows show status and info of first row
 - [x] If one run is started, other runs cannot be started (see bullet one)

Feature requests:

- [x] Facilitate navigation between tasks
- [x] List of tasks (also for navigation) 
- [x] Increase / Decrease Time during run
- [x] See list of viewers and their state
- [x] Force ready-state for viewer

**Comment by ppanopticon** [comment]
What is meant by "Task time reset in last 30 seconds"?

**Comment by sauterl** [comment]
@ppanopticon iirc, we discussed about resetting the task time in certain situations. I'm not sure whether we actually defined those situations.

**Comment by lucaro** [comment]
The idea was that there is a mechanism which extends the task time in case there is a submission shortly before the end of a task, in order to give other participants a chance to have their submissions also counted in case they happen shortly after.

**Comment by ppanopticon** [comment]
Agree! I'll refactor the two requests that have no place in this ticket into e separate one.

**Comment by ppanopticon** [comment]
What is meant by "All teams have an accepted submission results in task completed" (last item)?

**Comment by sauterl** [comment]
For KIS tasks, if all teams have an __accepted__ submission, then there is no point in having the task still open...

**Comment by ppanopticon** [comment]
Ahh okay. That also doesn't really belong in here.

**Comment by ppanopticon** [comment]
Done!
