### ISSUE TITLE
[Judgement] Remaining Submissions

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#78]
- [x] Endpoint to return remaining submissions info
- [ ] Frontend display of remaining submissions info

**Comment by lucaro** [comment]
Relevant endpoint added in 95da7e246f8daee2d6be557bd2803dcb8874d597

**Comment by lucaro** [comment]
@sauterl is the current endpoint sufficient or would you need additional information?

**Comment by sauterl** [comment]
@lucaro yes, this is sufficient, as far as my notes of our last discussion are correct, one has to sum up over all validators to get the remaining submissions for a particular task.
I will later this day push the frontend-updates and hopefully close this issue
