### ISSUE TITLE
Resume run

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#84]
- [x] load persistent run
- [x] resume loaded run
- [x] restart pipeline to enable judging

**Comment by ppanopticon** [comment]
Ongoing runs are resumed now in RunExecutor.init (lines 66 to 72). 

Now how exactly would I "restart the pipeline to enable judging"? @lucaro

**Comment by lucaro** [comment]
I see two options: either there is a mechanism in the loop which automatically finds submissions which are in an indeterminate state and adds them to an appropriate judgement manager if they are not already there, or, there is a CLI command to re-schedule submissions for judgement. The second option is probably the easier one, as this is not something that should happen very often, so some manual intervention should be fine. It would probably make sense to combine this with the recently added reset submission command, see e95b27269a8c50b964d1cab20dd00a559dc39cc1. Thoughts?

**Comment by ppanopticon** [comment]
Well I can live with either option! I suppose re-scheduling these submissions also comes in handy if there is a server crash for some reason.

But then the question remains:

- How to I get hold of the "appropriate" judgment manager (from within the SynchronousRunManager)?
- Do I need to start a new judgement manager when resuming up a SynchronousRunManager or are they spawned automatically?

**Comment by lucaro** [comment]
The submission validators are defined in the task description and are generated with the task run. The logic which restarts the run would just need to do something along the lines of:

```kotlin

competitionRun.runs.forEach {run ->
            run.data.submissions.filter { it.status == SubmissionStatus.INDETERMINATE }
                    .forEach { run.validator.validate(it) }
            
        }
```

Something similar would need to be called every time a submission status is reset.

**Comment by ppanopticon** [comment]
I added this to the initialisation of the SynchronousRunManager.

Imho, for the very few cases where we need to manually reset and re-schedule these submissions, a simple restart of the server would do, wouldn't it?

**Comment by lucaro** [comment]
I'd probably add the logic to the reset CLI command anyway, otherwise it is not very useful during a competition.

**Comment by lucaro** [comment]
What is preventing this from being closed? @ppanopticon

**Comment by ppanopticon** [comment]
From my side nothing :-)
