### ISSUE TITLE
Reference to MediaItem in DAOIndexer

### ISSUE THREAD

**Issue by ppanopticon** [lucaro/DRES#91]
The DAOIndexer seems to expect the MediaItem's name without preceding zeros (e.g. 1, 2, 231) as reference. However, some component that evaluates AVS submissions seems to expect the same name with preceding zeros (e.g. 00001, 00002, 00231). 

Hence, it is currently not possible to submit AVS tasks.

**Comment by lucaro** [comment]
I was unable to reproduce the issue, please reopen in case it persists.
