### ISSUE TITLE
[Bug] Chart export issue

### ISSUE THREAD

**Issue by mpas97** [lucaro/DRES#98]
Downloading the score chart doesn't work. Doesn't matter if I choose png or svg.
![89euzt3k](https://user-images.githubusercontent.com/9994218/84125611-10cfc400-aa3d-11ea-89b8-8df0c6c13140.png)

**Comment by mpas97** [comment]
It should look like the original instead:
<img width="320" alt="grafik" src="https://user-images.githubusercontent.com/9994218/84126116-cd298a00-aa3d-11ea-8523-bfcb3142519b.png">

**Comment by sauterl** [comment]
To be, this looks like an issue with, and our usage of: [ApexCharts](https://apexcharts.com/), as the downloaded SVG _contains_ all the information provided, however it's not properly _themed_.

As a work around / dirty-fix you could use an SVG Editor of your choice (I used [Inkscape](https://inkscape.org/)) to post-process the download and set the appropriate colors.

**Comment by lucaro** [comment]
The CSV export should however be correct, so in the worst case you can just plot the data yourself.

**Comment by sauterl** [comment]
@mpas97 Alternatively, you could download the CSV and plot it with your plotting-tool of choice. This way you would not be dependent on our dark theme

**Comment by sauterl** [comment]
After some investigation, this indeed seems to be an issue with the dark theme of the framework.
Unfortunately, it's not possible to only have the CSV Download and the others disabled, hence we'll have to keep the options there.

@lucaro We could discuss to provide our own CSV export and ultimately disable the context menu of the chart.

**Comment by lucaro** [comment]
In that case I would indeed opt for disabling the built-in export functionality and instead implement dedicated endpoints for various data exports. We should then specify what information should be in these exports, as it would probably make sense to have several of them, focusing on different aspects.

**Comment by sauterl** [comment]
I just created the [corresponding issue](https://github.com/apexcharts/apexcharts.js/issues/1669) on the framework's issue tracker.
Closing this for now

**Comment by sauterl** [comment]
Fortunately, apexcharts/apexcharts.js#1669 was already addressed and close.
As soon as the next release with this fix is published, the integrated apexcharts downloads will work again.
